# Single source of truth for Prompt Builder: blocks, options (EN/ES labels), prompt text.
BLOCKS = [
 dict(id="B1", key=("PHOTO","FOTO"), name=("Photo engine","Motor fotográfico"), hue="--h1", opts=[
  ("Realistic DSLR","Realista DSLR","RAW photo, photorealistic, real photograph, Canon EOS R5, 85mm lens, f/2.0, shallow depth of field, natural film grain, sharp focus, 8k uhd"),
  ("Fashion editorial","Editorial de moda","high-end fashion editorial photograph, medium format camera, 80mm lens, f/4, crisp detail, magazine quality, photorealistic"),
  ("Studio catalog","Catálogo de estudio","clean commercial catalog photograph, 50mm lens, f/8, everything in sharp focus, even exposure, photorealistic"),
  ("Cinematic ultra-real", "Cine ultra-real", "high-end photorealistic fashion photography, Canon EOS R5, 85mm lens, Kodak Portra 400 film aesthetic, subtle film grain, visible skin pores, individual eyelashes and hair strands, cinematic composition")]),
 dict(id="B2", key=("GLOW","BRI"), name=("Skin glow","Brillo de piel"), hue="--h2", opts=[
  ("Natural matte","Natural mate","natural matte skin finish, soft diffuse highlights"),
  ("Healthy glow","Glow saludable","healthy dewy skin glow, subtle natural sheen on cheekbones and shoulders"),
  ("Post-workout","Post-entreno","light post-workout glow, faint natural sheen of perspiration")]),
 dict(id="B3", key=("AGE","EDAD"), name=("Model age","Edad de la modelo"), hue="--h3", opts=[
  ("25","25 años","a 25-year-old woman, adult facial features"),
  ("30","30 años","a 30-year-old woman, adult facial features"),
  ("35","35 años","a 35-year-old woman, mature adult features"),
  ("40","40 años","a 40-year-old woman, mature adult features"),
  ("45","45 años","a 45-year-old woman, graceful mature features"),
  ("50","50 años","a 50-year-old woman, graceful mature features, subtle laugh lines")]),
 dict(id="B3.5", key=("ETHN","ETN"), name=("Heritage","Origen"), hue="--h3", zero=True, multi=True,
      mix={"strip": " heritage$", "tpl": "mixed {} heritage"}, opts=[
  ("Unspecified","Sin especificar",""),
  ("Slavic","Eslava","Slavic heritage"),
  ("Nordic","Nórdica","Nordic Scandinavian heritage"),
  ("Russian","Rusa","Russian heritage"),
  ("Latina","Latina","Latina heritage"),
  ("Mediterranean","Mediterránea","Mediterranean heritage"),
  ("Celtic","Celta","Celtic Irish heritage"),
  ("Afro-Caribbean","Afrocaribeña","Afro-Caribbean heritage"),
  ("African","Africana","African heritage"),
  ("Middle Eastern","Medio Oriente","Middle Eastern heritage"),
  ("South Asian","Sur de Asia","South Asian heritage"),
  ("East Asian","Asia oriental","East Asian heritage"),
  ("Southeast Asian","Sudeste asiático","Southeast Asian heritage"),
  ("Mixed","Mixta","mixed heritage"),
  ("Greek","Griega","Greek heritage"),
  ("Native American","Indígena norteamericana","Native American First Nations heritage")]),
 dict(id="B3.3", key=("EXPR","EXP"), name=("Expression","Expresión"), hue="--h3", opts=[
  ("Confident","Segura","confident relaxed expression, soft natural smile"),
  ("Cheerful","Alegre","bright friendly smile"),
  ("Elegant","Elegante","calm self-assured gaze"),
  ("Serene","Serena","serene warm expression"),
  ("Playful","Divertida","playful laughing expression"),
  ("Sweet & confident", "Dulce y segura", "sweet gentle expression, calm self-assured gaze, soft smile"),
  ("Dreamy & friendly", "Soñadora y amable", "dreamy contemplative expression, soft friendly smile, warm approachable look, calm and self-assured")]),
 dict(id="B3.1", key=("HAIR","CAB"), name=("Hair color","Color de cabello"), hue="--h3", multi=True,
      mix={"strip": " (dyed )?hair.*$", "tpl": "multi-tone hair blending {}"}, opts=[
  ("Honey blonde","Rubia miel","honey-blonde hair"),
  ("Platinum blonde","Rubia platino","platinum blonde hair"),
  ("Redhead","Pelirroja","copper-red hair"),
  ("Auburn","Caoba","auburn hair"),
  ("Chestnut","Castaño","chestnut-brown hair"),
  ("Ash brown","Castaño ceniza","ash-brown hair"),
  ("Black","Negro","jet-black hair"),
  ("Silver grey","Gris plata","silver-grey hair"),
  ("Pastel blue","Azul pastel","pastel blue dyed hair"),
  ("Electric blue","Azul eléctrico","vivid electric-blue dyed hair"),
  ("Pink","Rosa","soft pink dyed hair"),
  ("Lavender","Lavanda","lavender purple dyed hair"),
  ("Mint green","Verde menta","mint green dyed hair"),
  ("Blue-violet ombré","Degradado azul-violeta","blue to violet ombré dyed hair"),
  ("Rainbow","Multicolor arcoíris","rainbow multicolor dyed hair in pastel streaks"),
  ("Copper chestnut", "Castaño cobrizo", "chestnut-brown hair with copper and caramel highlights")]),
 dict(id="B3.4", key=("STYLE","PEI"), name=("Hairstyle","Peinado"), hue="--h3", opts=[
  ("Sleek straight","Liso perfecto","sleek straight hair"),
  ("Straight","Liso natural","straight hair"),
  ("Subtle waves","Ondas sutiles","subtle natural waves"),
  ("Wavy","Ondulado","wavy hair"),
  ("Beach waves","Ondas de playa","loose beach waves"),
  ("Curly","Rizado","curly hair"),
  ("Coily / afro","Muy rizado / afro","coily hair, afro hair"),
  ("High ponytail","Coleta alta","high ponytail"),
  ("Neat bun","Moño pulido","neat hair bun"),
  ("Messy bun","Moño suelto","loose messy bun with face-framing strands"),
  ("Pixie cut","Corte pixie","pixie cut"),
  ("Short bob","Bob corto","short bob cut"),
  ("Vine-strand waves", "Ondas con enredaderas", "long loose softly tousled hair with trailing thin vines and tiny white blossoms hanging like strands, small green leaves tucked in"),
  ("Straight vine strands", "Lisa con enredaderas", "long straight loose hair with trailing thin vines and tiny white blossoms hanging like strands, small green leaves tucked in"),
  ("Long windblown", "Larga al viento", "long flowing windblown hair, individual strands catching the light")]),
 dict(id="B3.2", key=("EYES","OJO"), name=("Eyes","Ojos"), hue="--h3", opts=[
  ("Blue","Azules","clear blue eyes"),("Green","Verdes","green eyes"),("Brown","Marrones","warm brown eyes"),("Hazel","Avellana","hazel eyes"),("Grey","Grises","grey eyes"),
  ("Amber gold", "Ámbar dorado", "luminous amber-gold eyes"),
  ("Magic green", "Verde mágico", "glowing vivid emerald-green eyes with a subtle magical light"),
  ("Vivid sapphire", "Zafiro intenso", "luminous vivid sapphire-blue eyes")]),
 dict(id="B4", key=("SKIN","PIEL"), name=("Skin tone","Piel y tono"), hue="--h4", opts=[
  ("Porcelain","Porcelana","fair porcelain skin with warm pink undertones, natural skin texture, visible pores"),
  ("Fair, freckles","Clara con pecas","fair skin with light freckles across the nose and cheeks, natural skin texture"),
  ("Olive","Oliva","olive skin tone with golden undertones, natural skin texture"),
  ("Tan","Morena","warm tan brown skin, natural skin texture, subtle color variation"),
  ("Deep","Oscura","deep brown skin with rich undertones, natural skin texture")]),
 dict(id="B5", key=("BODY","CUE"), name=("Body","Cuerpo"), hue="--h5", opts=[
  ("Athletic fit","Fitness atlética","fit athletic adult build, toned shoulders and arms, defined core, strong toned legs"),
  ("Lean pilates","Pilates esbelta","lean slender adult physique with long toned muscles, graceful upright posture"),
  ("Runner","Corredora","lean runner's build, defined legs, athletic adult proportions"),
  ("Natural","Natural","healthy natural adult body, soft curves, relaxed posture")]),
 dict(id="B6", key=("OUTFIT","VES"), name=("Outfit","Vestuario"), hue="--h6", opts=[
  ("Denim + white crop","Denim + crop blanco","white ribbed cotton crop top, high-waisted light-wash denim shorts, white canvas sneakers"),
  ("Black athletic","Deportivo negro","black sports crop top, matching high-waisted biker shorts, running shoes"),
  ("Summer linen","Lino verano","cream linen button-up crop top, high-waisted linen shorts, leather sandals"),
  ("Pastel knit","Punto pastel","sage green knit crop cardigan, high-waisted white tailored shorts, minimalist sandals"),
  ("Yoga set","Yoga set","dusty rose yoga set, fitted long-sleeve crop top and full-length leggings, barefoot"),
  ("Galactic heroine","Heroína galáctica","original superhero costume, full-coverage silver and teal bodysuit with geometric armor plates, short flowing cape, star emblem on the chest, knee-high boots"),
  ("Storm captain","Capitana tormenta","original superhero costume, full-coverage navy bodysuit with gold lightning-bolt piping, high collar, fingerless gloves, utility belt, armored boots"),
  ("Legend warrior","Guerrera de leyenda","original fantasy warrior costume, bronze breastplate over a long crimson tunic, leather bracers, ornate belt, sandal boots, round shield on her back"),
  ("Pirate","Pirata","pirate captain costume, white billowy blouse, burgundy brocade vest, tricorn hat, wide leather belt, tall boots, fitted dark trousers"),
  ("Astronaut","Astronauta","modern white astronaut suit with orange accents, mission patches, helmet held under one arm"),
  ("Samurai","Samurái","samurai-inspired costume, dark lacquered armor pieces over an indigo hakama and kimono, red cord details"),
  ("Flamenco","Flamenca","traditional red flamenco dress with white polka dots, ruffled sleeves and tiers, flower in the hair, shawl with fringe"),
  ("Cowgirl","Vaquera","western cowgirl outfit, suede fringe jacket, plaid shirt, high-waisted jeans, cowboy hat and boots"),
  ("Steampunk","Steampunk","steampunk explorer outfit, brown leather corset vest over a cream blouse, brass goggles on the hat, long skirt with buckles, gloves"),
  ("Forest elf","Elfa del bosque","original forest elf costume, long moss-green layered dress with leaf embroidery, hooded cape, elegant pointed ears, wooden bow"),
  ("Race driver","Piloto de carreras","racing driver suit, red and white fireproof jumpsuit with sponsor-free patches, helmet held at the hip"),
  ("Dominican carnival","Carnaval dominicano","Dominican carnival Diablo Cojuelo costume, vibrant full-coverage satin suit covered in mirrors, bells and ribbons, ornate horned mask held in her hand"),
  ("Brazil baiana","Baiana de Brasil","traditional Bahian samba-school baiana costume, wide hoop skirt with lace layers, embroidered blouse, colorful head wrap, bead necklaces"),
  ("Barranquilla cumbia","Cumbia de Barranquilla","Barranquilla carnival cumbia dancer outfit, long red, yellow and blue pollera skirt with ruffles, off-shoulder ruffled blouse, flower crown"),
  ("Oruro morenada","Morenada de Oruro","Oruro carnival morenada dancer costume, embroidered layered pollera skirt, sequined shawl, bowler hat"),
  ("Puno Candelaria","Candelaria de Puno","Candelaria festival dancer outfit from Puno, multiple bright layered polleras, embroidered jacket, bowler hat, woven shawl"),
  ("Venice carnival","Carnaval de Venecia","Venetian carnival gown, brocade bodice with long full skirt, ornate Colombina half-mask, feathered headpiece"),
  ("Retro soda shop","Cafetería retro","1950s retro soda-shop outfit, mint and cream letterman cardigan, mustard plaid pleated skirt, white ankle socks, penny loafers"),
  ("70s mystery sleuth","Detective años 70","1970s amateur detective outfit, mustard corduroy jacket, teal turtleneck, brown bell-bottom trousers, platform boots, flashlight in hand"),
  ("Farm-town hero","Heroína de pueblo","small-town farm outfit, forest green flannel shirt, worn denim jacket, straight jeans, leather work boots"),
  ("Emerald heroine (cape)","Heroína esmeralda (capa)","original superhero costume, full-coverage emerald and silver bodysuit, short silver cape, stylized leaf emblem on the chest, knee-high silver boots"),
  ("Emerald heroine (no cape)","Heroína esmeralda (sin capa)","original superhero costume, full-coverage emerald and silver bodysuit with sleek armored panels, stylized leaf emblem on the chest, silver gauntlets, knee-high silver boots, no cape"),
  ("Forest princess (short)", "Princesa del bosque (corto)", "original forest princess outfit, dress made of layered green leaves, vine-laced bodice, puffed leaf sleeves, short ruffled leaf skirt ending above the knee, vine-wrapped heeled sandals, no wings"),
  ("Forest princess (gown)", "Princesa del bosque (largo)", "original forest princess gown made of layered green leaves, vine-laced bodice, puffed leaf sleeves, flowing full-length leaf skirt with tiny white blossoms, no wings"),
  ("Lily princess (short)", "Princesa lirio (corto)", "original flower princess dress made of layered white star-shaped lily petals with pale green tips, fitted petal bodice with fine golden stamen embroidery, soft chiffon underlayer, tiny crystal dewdrops, thin green vine belt, short petal skirt ending well above the knee, satin heeled sandals, no wings"),
  ("Lily princess (gown)", "Princesa lirio (largo)", "original flower princess gown made of cascading white star-shaped lily petals with pale green tips, fitted petal bodice with fine golden stamen embroidery, sheer chiffon sleeves, tiny crystal dewdrops, thin green vine belt, flowing full-length petal skirt with a short train, no wings"),
  ("Midnight moth heroine", "Heroína polilla nocturna", "original superhero costume, glossy black finely pebbled textured fabric with subtle iridescent sheen, fine silver moth-wing vein patterns tracing the gloves, forearms and sides, feminine fitted cropped long-sleeve top ending just below the bust, high-waisted fitted trousers, long gloves, large metallic silver moth emblem across the chest, no mask"),
  ("Midnight moth (crop)", "Polilla nocturna (top corto)", "original superhero costume, glossy black finely pebbled textured fabric with subtle iridescent sheen, fine silver moth-wing vein patterns tracing the gloves, forearms and sides, sleek two-piece design, cropped long-sleeve top, matching fitted trousers, long gloves, large metallic silver moth emblem across the chest")]),
 dict(id="B6.1", key=("ACC","ACC"), name=("Accessories","Accesorios"), hue="--h6", zero=True, multi=True, opts=[
  ("None","Ninguno",""),("Emerald necklace","Collar esmeralda","emerald pendant necklace on a fine gold chain"),("Gold hoops","Aros dorados","small gold hoop earrings"),("Sports watch","Reloj deportivo","minimalist sports watch"),("Cap","Gorra","beige baseball cap"),
  ("Sunglasses","Gafas de sol","oversized tortoiseshell sunglasses"),
  ("Straw hat","Sombrero de paja","wide-brim straw hat"),
  ("Silk scarf","Pañuelo de seda","patterned silk scarf"),
  ("Pearl earrings","Aretes de perla","small pearl stud earrings"),
  ("Gold bracelets","Pulseras doradas","stack of thin gold bracelets"),
  ("Tote bag","Bolso tote","canvas tote bag on the shoulder"),
  ("Yoga mat","Esterilla de yoga","rolled yoga mat under one arm"),
  ("Delicate henna","Henna delicada","delicate golden-brown henna design on the backs of the hands and fingers, fine floral and vine lines, subtle and elegant"),
  ("Moth-wing mask", "Antifaz ala de polilla", "sleek silver moth-wing shaped eye mask with open eye holes, eyes clearly visible")]),
 dict(id="B6.2", key=("MASK","MAS"), name=("Face covering","Máscara"), hue="--h6", zero=True, opts=[
  ("None","Ninguna",""),
  ("Moth-wing eye mask","Antifaz ala de polilla","sleek silver moth-wing shaped eye mask with open eye holes, eyes clearly visible"),
  ("Venetian lace mask","Antifaz de encaje","delicate black lace eye mask with open eye holes, eyes clearly visible"),
  ("Gold filigree half-mask","Media máscara filigrana","ornate gold filigree half-mask covering the upper face, open eye holes, eyes clearly visible"),
  ("Feathered masquerade","Antifaz con plumas","masquerade eye mask with soft feathers and small crystals, open eye holes, eyes clearly visible"),
  ("Lily petal mask","Antifaz de pétalos","eye mask made of small white lily petals with pale green tips, open eye holes, eyes clearly visible"),
  ("Crystal eye mask","Antifaz de cristales","eye mask covered in tiny clear crystals that catch the light, open eye holes, eyes clearly visible"),
  ("Sheer face veil","Velo sobre el rostro","sheer delicate tulle veil falling over the face from a small headpiece, face softly visible through it"),
  ("Lower-face veil","Velo bajo los ojos","sheer chiffon veil covering the nose and mouth, held by a thin chain, eyes uncovered"),
  ("Desert scarf wrap","Pañuelo del desierto","light linen scarf wrapped over the head and lower face, eyes uncovered"),
  ("Futuristic visor","Visor futurista","sleek translucent iridescent visor across the eyes, futuristic design")]),
 dict(id="B7", key=("CAM","CAM"), name=("Framing & pose","Encuadre y pose"), hue="--h7", opts=[
  ("Full body 3/4","Cuerpo entero 3/4","full body shot, head to toe framing, standing relaxed, three-quarter turn, looking at camera"),
  ("Half body","Medio cuerpo","medium shot from the waist up, looking at camera"),
  ("Portrait","Retrato","close-up portrait, head and shoulders"),
  ("Walking","Caminando","full body shot, walking toward camera, natural mid-stride motion"),
  ("Seated","Sentada","full body shot, sitting casually on a low wooden stool, relaxed posture"),
  ("Confident stance", "Postura segura", "full body shot, standing tall, confident regal posture, shoulders back, chin slightly raised, looking at camera"),
  ("On the girder", "En la viga", "full body, reclining on a steel girder high above the city, one arm raised behind her head, relaxed diagonal body line"),
  ("Sitting on the edge", "Sentada en el borde", "full body, sitting on the edge of a steel girder high above the city, one knee drawn up with her forearm resting on it, the other leg hanging over the edge, leaning back on one hand, head tilted, gazing down at the city"),
  ("Silk hammock", "Hamaca de seda", "full body, reclining comfortably in a hammock woven only from thin shimmering silver threads, loose cocoon-like strands catching the light, strung between two stone pillars, one arm resting behind her head, one leg gently bent, relaxed and at ease"),
  ("Suspended in silk", "Suspendida en seda", "full body, suspended mid-air in a sweeping web of thin glowing silver threads stretched between the terrace columns, body in a dynamic diagonal line, one arm raised behind her head, the other hand gripping a silk strand, hair and loose silk threads streaming in the wind, silk strands crossing the foreground"),
  ("Lying on silk net", "Recostada en red de seda", "full body, reclining gracefully on a large taut radial net made only of thin glowing silver threads, the net clearly visible beneath and around her and supporting her weight, body in a relaxed diagonal line, one arm raised behind her head, the other hand resting on the net, one knee slightly bent, hair spilling across the net and lifted by the wind"),
  ("Full body (framing only)", "Cuerpo entero (solo encuadre)", "full body shot, head to toe framing"),
  ("Wide shot", "Plano general", "wide full body shot, figure smaller in the frame, surroundings emphasized")]),
 dict(id="B7.2", key=("POSE","POS"), name=("Pose","Postura"), hue="--h7", zero=True, opts=[
  ("From framing","Según encuadre",""),
  ("Standing tall","De pie, segura","standing tall, confident posture, shoulders back"),
  ("Sitting","Sentada","sitting gracefully, relaxed posture"),
  ("Reclining","Recostada","reclining gracefully, one arm resting behind her head, one knee gently bent"),
  ("Kneeling","De rodillas","kneeling on one knee, upright torso"),
  ("Walking","Caminando","walking forward, natural mid-stride"),
  ("Suspended diagonal","Suspendida en diagonal","suspended in a dynamic diagonal line, one hand gripping a strand, hair streaming in the wind"),
  ("Arms raised","Brazos en alto","standing with both arms raised triumphantly toward the sky"),
  ("Leaning on a wall","Apoyada en la pared","leaning casually with one shoulder against a wall, relaxed"),
  ("Lying on her side","De lado, sobre el codo","lying on her side, propped up on one elbow, relaxed"),
  ("Cross-legged","Piernas cruzadas","sitting cross-legged, upright and relaxed"),
  ("Over the shoulder","Mirando por encima del hombro","standing turned away, looking back over her shoulder"),
  ("Twirling","Girando","caught mid-twirl, hair and clothing flowing with the motion"),
  ("Hero crouch","Agachada heroica","crouching low in a ready stance, one hand touching the ground"),
  ("Yoga lotus","Yoga: loto","seated in lotus pose, spine tall"),
  ("Yoga tree","Yoga: árbol","standing in tree pose, balanced on one leg"),
  ("Yoga warrior II","Yoga: guerrero II","in warrior II yoga pose, arms extended, strong stance")]),
 dict(id="B7.3", key=("PLACE","LUG"), name=("Place","Lugar"), hue="--h7", zero=True, opts=[
  ("None","Ninguno",""),
  ("Steel girder","Viga de acero","on a steel girder high above the city"),
  ("Silk hammock","Hamaca de seda","in a hammock woven only from thin shimmering silver threads, loose cocoon-like strands catching the light, strung between two stone pillars"),
  ("Silk net","Red de seda","on a large taut radial net made only of thin glowing silver threads, the net clearly visible beneath and around her and supporting her weight"),
  ("Pyramid tower top","Cima de torre pirámide","on the very top of a glass pyramid-shaped skyscraper, the entire city spread out around and below her to the horizon"),
  ("Tower spire top","Cima de una torre","on the small platform at the very top of a tall tower spire, the entire city spread out around and below her to the horizon"),
  ("Rooftop ledge","Cornisa de azotea","on the stone ledge of a rooftop terrace, city skyline behind her")]),
 dict(id="B7.4", key=("HANDS","MAN"), name=("Hands","Manos"), hue="--h7", zero=True, opts=[
  ("Natural","Naturales",""),
  ("Hands on hips","Manos en la cintura","hands on hips"),
  ("Arms crossed","Brazos cruzados","arms loosely crossed"),
  ("Hand in hair","Mano en el pelo","one hand running through her hair"),
  ("Hand on chin","Mano en el mentón","one hand resting lightly under her chin"),
  ("Hands clasped","Manos juntas al frente","hands gently clasped in front of her"),
  ("Holding a flower","Sosteniendo una flor","holding a single white flower in one hand"),
  ("Reaching out","Mano hacia la cámara","one hand reaching softly toward the camera"),
  ("Hands in pockets","Manos en los bolsillos","hands tucked into her pockets"),
  ("Hands at heart","Manos al pecho (namasté)","palms pressed together at her heart"),
  ("Light in palm","Luz en la palma","a small glowing light floating above her open palm"),
  ("Arm behind head","Brazo detrás de la cabeza","one arm raised and resting behind her head"),
  ("Touching the mask","Tocando la máscara","fingertips lightly touching the edge of her mask")]),
 dict(id="B7.1", key=("ANGLE","ANG"), name=("Camera angle","Ángulo de cámara"), hue="--h7", opts=[
  ("Eye-level","A la altura de los ojos","eye-level shot, neutral natural perspective"),
  ("Low angle","Contrapicado","low angle shot looking up at the subject, powerful heroic perspective"),
  ("High angle","Picado","high angle shot looking down at the subject"),
  ("Bird's-eye / top-down","Cenital","bird's-eye view, top-down overhead shot"),
  ("Worm's-eye","Nadir","worm's-eye view from the ground looking straight up, dramatic height"),
  ("Dutch angle","Ángulo holandés","dutch angle, tilted horizon, dynamic tension"),
  ("Over-the-shoulder","Sobre el hombro","over-the-shoulder shot, blurred shoulder in the foreground"),
  ("Profile / side view","Perfil","side view profile shot"),
  ("Hip level","Altura de cadera","hip-level shot, camera at waist height"),
  ("Knee level","Altura de rodilla","knee-level shot, camera low near the knees"),
  ("Aerial drone","Dron aéreo","aerial drone shot from high above"),
  ("POV","Punto de vista (POV)","first-person point of view shot"),
  ("High 3/4 tilt", "3/4 alto inclinado", "dramatic high three-quarter angle, camera elevated and looking diagonally down at her, slight dynamic camera tilt, deep background with city lights bokeh")]),
 dict(id="B8", key=("LIGHT","LUZ"), name=("Lighting","Luz"), hue="--h8", opts=[
  ("Soft studio","Estudio suave","soft even studio lighting, large softbox, gentle shadows"),
  ("Golden hour","Hora dorada","warm golden hour sunlight, soft rim light"),
  ("Window","Ventana","soft natural window light from the side"),
  ("Overcast","Nublado","bright overcast daylight, soft shadowless light"),
  ("Dramatic rim light", "Contraluz dramático", "dramatic cinematic backlight at dusk, glowing rim light outlining her silhouette and hair, high contrast, warm city lights bokeh")]),
 dict(id="B11", key=("BG","FON"), name=("Background","Fondo"), hue="--h4", opts=[
  ("White void","Void blanco","seamless pure white background, infinite white studio void, soft contact shadow on the floor"),
  ("Neutral grey","Gris neutro","seamless light grey studio backdrop"),
  ("Paris","París","Paris cityscape with the Eiffel Tower in the background, creamy bokeh"),
  ("Beach","Playa","tropical beach at sunset, palm trees, soft ocean bokeh"),
  ("Yoga studio","Sala de yoga","bright yoga studio, light wooden floor, large windows, green plants"),
  ("City street","Calle urbana","sunny city street, modern storefronts, soft background blur"),
  ("Palace garden", "Palacio jardín", "sunlit marble palace conservatory, white columns and arches, climbing roses, polished marble floor, scattered softly glowing blue petals"),
  ("Cloud terrace", "Terraza en las nubes", "ivy-covered stone arcade on a palace terrace above the clouds, bright sky"),
  ("City from above", "Ciudad desde arriba", "dramatic overhead view of a busy city street far below, yellow taxis, traffic, skyscrapers, shallow depth of field"),
  ("Night city from above", "Ciudad de noche desde arriba", "dizzying aerial view of a city at night far below, neon lights blurred into haze, streams of yellow taxis, towering skyscrapers on both sides"),
  ("Rooftop terrace skyline", "Terraza con vista", "elegant rooftop terrace with a stone balustrade and potted plants, wide city skyline across the background at dusk, warm city lights, shallow depth of field"),
  ("Terrace silk net", "Terraza con red de seda", "rooftop terrace at dusk with a giant radial net made only of thin glowing silver threads, like a luminous web, anchored between stone columns, evenly woven geometric mesh pattern, strands crossing the foreground, city skyline and warm lights in the background"),
  ("Open sky", "Cielo abierto", "clear blue sky, bright daylight, distant horizon")]),
]
NEG = "cartoon, anime, 3d render, plastic skin, airbrushed, deformed hands, extra fingers, distorted anatomy, blurry, watermark, text, logo, cropped feet, teenager, childlike features"
DEFAULT = {"B1":0,"B2":0,"B3":0,"B3.5":[1],"B3.3":1,"B3.1":[0],"B3.4":8,"B3.2":1,"B4":2,"B5":1,"B6":21,"B6.1":[],"B6.2":0,"B7":0,"B7.2":0,"B7.3":0,"B7.4":0,"B7.1":0,"B8":0,"B11":5}  # Venice carnival in the city (chosen by Alex)

# Presets: ready-made combinations (all 25-year-old, Slavic). Not part of the prompt library, so no version bump.
PRESETS = [
 ("Forest princess", "Princesa del bosque", "PHOTO1 GLOW2 AGE1 ETHN1 EXPR6 HAIR16 STYLE13 EYES7 SKIN2 BODY2 OUTFIT28 ACC0 MASK0 CAM6 POSE0 PLACE0 HANDS0 ANGLE1 LIGHT2 BG7 | perchance | one"),
 ("Lily princess", "Princesa lirio", "PHOTO2 GLOW2 AGE1 ETHN1 EXPR6 HAIR1 STYLE14 EYES8 SKIN1 BODY2 OUTFIT31 ACC12 MASK0 CAM6 POSE0 PLACE0 HANDS0 ANGLE2 LIGHT2 BG8 | perchance | one"),
 ("Yoga catalog", "Catálogo de yoga", "PHOTO3 GLOW1 AGE1 ETHN1 EXPR4 HAIR6 STYLE9 EYES2 SKIN1 BODY2 OUTFIT5 ACC0 MASK0 CAM1 POSE0 PLACE0 HANDS0 ANGLE1 LIGHT1 BG1 | perchance | one"),
 ("Beach sunset", "Playa al atardecer", "PHOTO2 GLOW2 AGE1 ETHN1 EXPR2 HAIR1 STYLE5 EYES1 SKIN2 BODY1 OUTFIT3 ACC6 MASK0 CAM4 POSE0 PLACE0 HANDS0 ANGLE1 LIGHT2 BG4 | perchance | one"),
 ("Paris street style", "Estilo urbano en París", "PHOTO2 GLOW1 AGE1 ETHN1 EXPR3 HAIR5 STYLE3 EYES4 SKIN1 BODY2 OUTFIT4 ACC7+8 MASK0 CAM4 POSE0 PLACE0 HANDS0 ANGLE9 LIGHT4 BG3 | perchance | one"),
 ("Urban fitness", "Fitness urbano", "PHOTO1 GLOW3 AGE1 ETHN1 EXPR1 HAIR2 STYLE8 EYES1 SKIN1 BODY1 OUTFIT2 ACC3 MASK0 CAM4 POSE0 PLACE0 HANDS0 ANGLE2 LIGHT2 BG6 | perchance | one"),
 ("Emerald heroine", "Heroína esmeralda", "PHOTO1 GLOW2 AGE1 ETHN1 EXPR1 HAIR7 STYLE8 EYES2 SKIN1 BODY1 OUTFIT27 ACC0 MASK0 CAM6 POSE0 PLACE0 HANDS0 ANGLE2 LIGHT2 BG6 | perchance | one"),
 ("Flamenco night", "Noche flamenca", "PHOTO2 GLOW2 AGE1 ETHN1 EXPR3 HAIR7 STYLE9 EYES3 SKIN3 BODY4 OUTFIT12 ACC2 MASK0 CAM1 POSE0 PLACE0 HANDS0 ANGLE1 LIGHT2 BG6 | perchance | one"),
 ("Pastel dream", "Sueño pastel", "PHOTO2 GLOW2 AGE1 ETHN1 EXPR5 HAIR9+12 STYLE4 EYES8 SKIN1 BODY2 OUTFIT23 ACC0 MASK0 CAM1 POSE0 PLACE0 HANDS0 ANGLE1 LIGHT1 BG2 | perchance | one"),
 ("Midnight moth", "Polilla nocturna", "PHOTO4 GLOW1 AGE1 ETHN1 EXPR4 HAIR2 STYLE15 EYES5 SKIN1 BODY2 OUTFIT32 ACC0 MASK0 CAM7 POSE0 PLACE0 HANDS0 ANGLE3 LIGHT4 BG9 | venice | nl"),
 ("The Silver Weaver", "La Tejedora de Plata", "PHOTO4 GLOW1 AGE1 ETHN1 EXPR7 HAIR2 STYLE15 EYES5 SKIN1 BODY2 OUTFIT32 ACC0 MASK0 CAM8 POSE0 PLACE0 HANDS0 ANGLE3 LIGHT4 BG10 | venice | nl"),
 ("Moth silk terrace", "Terraza de seda", "PHOTO4 GLOW2 AGE1 ETHN1 EXPR7 HAIR2 STYLE15 EYES5 SKIN1 BODY2 OUTFIT33 ACC0 MASK1 CAM12 POSE3 PLACE3 HANDS0 ANGLE13 LIGHT5 BG12 | venice | nl"),
 ("Top of the city", "En la cima de la ciudad", "PHOTO4 GLOW1 AGE1 ETHN1 EXPR1 HAIR2 STYLE15 EYES5 SKIN1 BODY2 OUTFIT33 ACC0 MASK1 CAM13 POSE7 PLACE5 HANDS0 ANGLE1 LIGHT2 BG13 | venice | nl"),
 ("Studio portrait", "Retrato de estudio", "PHOTO1 GLOW1 AGE1 ETHN1 EXPR4 HAIR3 STYLE4 EYES2 SKIN2 BODY4 OUTFIT3 ACC8 MASK0 CAM3 POSE0 PLACE0 HANDS0 ANGLE1 LIGHT3 BG2 | perchance | one"),
]

# Library version: bump when any prompt text changes, so recipes record which texts they used.
LIB_VERSION = "1.22"  # 1.22: 9 more poses (incl. yoga) and a Hands block; 1.21: Face covering block (MASK), moth mask with visible eyes; 1.20: silk nets/hammock described as glowing threads (Venice drew satin fabric); 1.19: POSE and PLACE blocks, framing-only CAM 12–13, open sky; 1.18: clearer two-piece moth suit and reclining net pose, high 3/4 tilt angle; 1.17: lying-on-silk-net pose, terrace silk-net background; 1.16: moth crop suit, moth-wing mask, suspended-in-silk pose, dramatic rim light; 1.15: silk hammock pose, rooftop terrace skyline; 1.14: shorter short dresses, textured moth suit, dreamy expression, edge pose, night city; 1.13: cinematic photo, windblown hair, midnight moth heroine, girder pose, city from above; 1.12: delicate henna accessory (ACC12); 1.11: lily princess outfits 30–31; 1.10: mix heritages (ETHN4+14) and hair colors (HAIR3+10); 1.9: Forest princess set (vine hair, eyes, outfits 28–29, confident stance, palace backgrounds); 1.8: 7 dyed hair colors, outfits 23–27, heritage Greek and Native American; 1.7: new HERITAGE block (ETHN), Slavic by default; 1.6: accessories allow several (ACC1+3) and 7 new ones; 1.5: new default base; 1.4: outfits 18–22; 1.3: yoga catalog base

PLATFORMS = {  # separator default + transforms applied to the prompt text
    "venice":    {"label": "Venice AI",    "sep": "nl"},
    "seaart":    {"label": "SeaArt",       "sep": "nl", "weights": ["B6", "B11"]},
    "perchance": {"label": "Perchance AI", "sep": "one", "drop": ["8k uhd", "RAW photo", "real photograph", "natural film grain", "magazine quality"]},
    "gen":       {"label": "Generic",      "sep": "nl"},
}
DEFAULT_PLATFORM = "perchance"
# How blocks are joined. Frozen per version together with the platform rules and defaults.
SEPARATORS = {
    "nl":    {"joiner": ",\n"},
    "one":   {"joiner": ", "},
    "tag":   {"joiner": ",\n", "prefix": True},
    "break": {"joiner": ",\nBREAK\n"},
}

# Notes about block combinations. Shown as notes, grouped by kind; the tool never changes the user's choices.
#   incompatible : the two blocks ask for opposite things
#   out_of_frame : details that the chosen framing will not show
#   test         : may work, but depends on the model — try it with a fixed seed
# A rule matches when block a is one of a_opts and (if given) block b is one of b_opts. Indexes are 0-based.
CONFLICTS = [
    dict(kind="test", a="B7.4", a_opts=list(range(1, 13)), b="B7.2", b_opts=[3, 6, 7, 13, 16],
         en="This POSE already places the arms or hands; a HANDS choice may clash with it.",
         es="Esta POSTURA ya define brazos o manos; una opción de MANOS puede chocar."),
    dict(kind="test", a="B7.4", a_opts=[12], b="B6.2", b_opts=[0],
         en="HANDS 12 touches the mask, but no MASK is chosen.",
         es="MANOS 12 toca la máscara, pero no hay MÁSCARA elegida."),
    dict(kind="incompatible", a="B6.2", a_opts=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], b="B6.1", b_opts=[13],
         en="Two masks: the moth-wing mask in ACC and a face covering in MASK. Keep only one.",
         es="Dos máscaras: el antifaz de polilla en ACC y una máscara en MÁSCARA. Deja solo una."),
    dict(kind="test", a="B6.2", a_opts=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], b="B6", b_opts=[21],
         en="The Venice carnival outfit already includes a mask; a second one may clash.",
         es="El vestuario de carnaval de Venecia ya trae antifaz; otra máscara puede chocar."),
    dict(kind="test", a="B7.2", a_opts=[1, 2, 3, 4, 5, 6, 7], b="B7", b_opts=[0, 3, 4, 5, 6, 7, 8, 9, 10],
         en="This CAM option already includes a pose. With POSE, use a framing-only CAM: 2, 3, 12 or 13.",
         es="Esta opción de CAM ya trae una pose. Con POSTURA usa un encuadre simple: CAM 2, 3, 12 o 13."),
    dict(kind="test", a="B7.3", a_opts=[1, 2, 3, 4, 5, 6], b="B7", b_opts=[0, 3, 4, 5, 6, 7, 8, 9, 10],
         en="This CAM option already includes a pose or place. With PLACE, use a framing-only CAM: 2, 3, 12 or 13.",
         es="Esta opción de CAM ya trae una pose o un lugar. Con LUGAR usa un encuadre simple: CAM 2, 3, 12 o 13."),
    dict(kind="incompatible", a="B6.1", a_opts=[4], b="B6.1", b_opts=[6],
         en="Cap and straw hat together: pick one headwear.",
         es="Gorra y sombrero de paja a la vez: elige una sola prenda para la cabeza."),
    dict(kind="incompatible", a="B6.1", a_opts=[4, 6], b="B6", b_opts=[8, 12, 19, 20, 21],
         en="This outfit already includes headwear (tricorn, cowboy hat, bowler hat or feathered headpiece); a cap or straw hat will clash.",
         es="Este vestuario ya incluye algo en la cabeza (tricornio, sombrero vaquero, bombín o tocado de plumas); la gorra o el sombrero de paja chocarán."),
    dict(kind="incompatible", a="B7.1", a_opts=[7], b="B7", b_opts=[0, 1],
         en="ANGLE 8 (profile) vs. this framing, which asks for a three-quarter turn or looking at the camera.",
         es="ÁNGULO 8 (perfil) frente a este encuadre, que pide giro de tres cuartos o mirar a cámara."),
    dict(kind="out_of_frame", a="B7", a_opts=[1, 2],
         en="Half-body and portrait framings crop the lower body: shorts, footwear and leg details from OUTFIT or BODY won't show.",
         es="El medio cuerpo y el retrato recortan la parte baja: el short, el calzado y los detalles de piernas de VESTUARIO o CUERPO no se verán."),
    dict(kind="test", a="B7.1", a_opts=[3, 4], b="B7", b_opts=[2],
         en="Top-down or worm's-eye with a head-and-shoulders portrait can give unusual crops. Test with a fixed seed.",
         es="Cenital o nadir con un retrato de cabeza y hombros puede dar recortes raros. Pruébalo con un seed fijo."),
    dict(kind="test", a="B7.1", a_opts=[10], b="B11", b_opts=[0, 1],
         en="An aerial drone shot over a studio backdrop is unusual; models may add a landscape. Test it.",
         es="Un plano de dron sobre un fondo de estudio es poco común; el modelo puede inventar un paisaje. Pruébalo."),
    dict(kind="test", a="B7.1", a_opts=[11], b="B7", b_opts=[0, 1],
         en="POV plus 'looking at camera' may read as a selfie. Test it.",
         es="POV más 'mirando a cámara' puede salir como selfie. Pruébalo."),
]
